nmHoistingLimits: workspaces
nodeLinker: node-modules
checksumBehavior: update
packageExtensions:
  "@ai-sdk/react@*":
    dependencies:
      zod: 4.3.6
  "@streamdown/cjk@*":
    dependencies:
      unified: ^11.0.0
  "remark-cjk-friendly-gfm-strikethrough@*":
    dependencies:
      micromark: ^4.0.0
  "remark-cjk-friendly@*":
    dependencies:
      micromark: ^4.0.0
