import { defineConfig } from 'vitest/config'

export default defineConfig({
  test: {
    projects: [
      // Core package - use its own vitest config
      './core',

      // Web-app package - use its own vitest config
      './web-app',

      // Bundled extensions - keep runtime extension contracts in the root lane
      './extensions/assistant-extension',
      './extensions/conversational-extension',
      './extensions/download-extension',
      './extensions/llamacpp-extension',
      './extensions/llamacpp-api',

      // Test infrastructure guardrails
      './scripts/testing',
    ],
    coverage: {
      // Root `coverage/` is the Vitest default and industry convention (Istanbul/v8).
      // Do not commit it — see .gitignore. Regenerated by `yarn test:coverage`.
      provider: 'v8',
      reportsDirectory: './coverage',
      clean: true,
      cleanOnRerun: true,
      reporter: ['text', 'json', 'json-summary', 'html', 'lcov'],
      exclude: [
        'docs',
        '**/*/dist',
        'node_modules',
        'coverage',
        'report',
        'src/**/*.test.ts',
        'src/**/*.test.tsx',
        'src/test/**/*',
        'extensions',
      ],
    },
  },
})
