export const localStorageKey = {
  LeftPanel: 'left-panel',
  threads: 'threads',
  messages: 'messages',
  theme: 'theme',
  modelProvider: 'model-provider',
  modelSources: 'model-sources',
  settingInterface: 'setting-appearance',
  settingGeneral: 'setting-general',
  axBiSessions: 'ax-bi-sessions',
  axBiMcpToken: 'ax-bi-mcp-token',
  /** Electron-only dev/smoke override for the AX BI MCP endpoint. */
  axBiMcpUrlOverride: 'ax-bi-mcp-url-override',
  /** Electron slim AX BI view: last dataset picked in the dataset selector. */
  axBiLastDataset: 'ax-bi-last-dataset',

  settingCodeBlock: 'setting-code-block',
  settingLocalApiServer: 'setting-local-api-server',
  settingProxyConfig: 'setting-proxy-config',
  settingHardware: 'setting-hardware',
  settingVulkan: 'setting-vulkan',
  toolApproval: 'tool-approval',
  toolAvailability: 'tool-availability',
  mcpGlobalPermissions: 'mcp-global-permissions',
  lastUsedModel: 'last-used-model',
  lastUsedAssistant: 'last-used-assistant',
  favoriteModels: 'favorite-models',
  setupCompleted: 'setup-completed',
  startupHintDismissed: 'startup-hint-dismissed',
  workspaceMode: 'workspace-mode',
  threadManagement: 'thread-management',
  chatOrganization: 'chat-organization',
  modelSupportCache: 'ax-studio-model-support-cache',
  recentSearches: 'recent-searches',
  memoryStore: 'memory-store',
  localKnowledgeStore: 'local-knowledge-store',
  fileRegistryStore: 'file-registry-store',
  routerSettings: 'router-settings',
  globalShortcut: 'global-shortcut',
  voiceSettings: 'voice-settings',
}
