export const localStorageKey = {
  LeftPanel: 'left-panel',
  threads: 'threads',
  messages: 'messages',
  theme: 'theme',
  modelProvider: 'model-provider',
  modelSources: 'model-sources',
  settingInterface: 'setting-appearance',
  settingGeneral: 'setting-general',
  axBiSessions: 'ax-bi-sessions',

  settingCodeBlock: 'setting-code-block',
  settingLocalApiServer: 'setting-local-api-server',
  settingProxyConfig: 'setting-proxy-config',
  settingHardware: 'setting-hardware',
  settingVulkan: 'setting-vulkan',
  toolApproval: 'tool-approval',
  toolAvailability: 'tool-availability',
  mcpGlobalPermissions: 'mcp-global-permissions',
  lastUsedModel: 'last-used-model',
  lastUsedAssistant: 'last-used-assistant',
  favoriteModels: 'favorite-models',
  setupCompleted: 'setup-completed',
  workspaceMode: 'workspace-mode',
  threadManagement: 'thread-management',
  modelSupportCache: 'ax-studio-model-support-cache',
  recentSearches: 'recent-searches',
  memoryStore: 'memory-store',
  localKnowledgeStore: 'local-knowledge-store',
  fileRegistryStore: 'file-registry-store',
  routerSettings: 'router-settings',
}
