/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as HubIndexRouteImport } from './routes/hub/index'
import { Route as ThreadsThreadIdRouteImport } from './routes/threads/$threadId'
import { Route as SettingsGeneralRouteImport } from './routes/settings/general'
import { Route as SettingsAxEngineRouteImport } from './routes/settings/ax-engine'
import { Route as HubModelIdRouteImport } from './routes/hub/$modelId'
import { Route as SettingsProvidersIndexRouteImport } from './routes/settings/providers/index'
import { Route as SettingsProvidersProviderNameRouteImport } from './routes/settings/providers/$providerName'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const HubIndexRoute = HubIndexRouteImport.update({
  id: '/hub/',
  path: '/hub/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreadsThreadIdRoute = ThreadsThreadIdRouteImport.update({
  id: '/threads/$threadId',
  path: '/threads/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: '/settings/general',
  path: '/settings/general',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAxEngineRoute = SettingsAxEngineRouteImport.update({
  id: '/settings/ax-engine',
  path: '/settings/ax-engine',
  getParentRoute: () => rootRouteImport,
} as any)
const HubModelIdRoute = HubModelIdRouteImport.update({
  id: '/hub/$modelId',
  path: '/hub/$modelId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProvidersIndexRoute = SettingsProvidersIndexRouteImport.update({
  id: '/settings/providers/',
  path: '/settings/providers/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProvidersProviderNameRoute =
  SettingsProvidersProviderNameRouteImport.update({
    id: '/settings/providers/$providerName',
    path: '/settings/providers/$providerName',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hub/$modelId': typeof HubModelIdRoute
  '/settings/ax-engine': typeof SettingsAxEngineRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/threads/$threadId': typeof ThreadsThreadIdRoute
  '/hub/': typeof HubIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/settings/providers/$providerName': typeof SettingsProvidersProviderNameRoute
  '/settings/providers/': typeof SettingsProvidersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hub/$modelId': typeof HubModelIdRoute
  '/settings/ax-engine': typeof SettingsAxEngineRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/threads/$threadId': typeof ThreadsThreadIdRoute
  '/hub': typeof HubIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/settings/providers/$providerName': typeof SettingsProvidersProviderNameRoute
  '/settings/providers': typeof SettingsProvidersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hub/$modelId': typeof HubModelIdRoute
  '/settings/ax-engine': typeof SettingsAxEngineRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/threads/$threadId': typeof ThreadsThreadIdRoute
  '/hub/': typeof HubIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/settings/providers/$providerName': typeof SettingsProvidersProviderNameRoute
  '/settings/providers/': typeof SettingsProvidersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hub/$modelId'
    | '/settings/ax-engine'
    | '/settings/general'
    | '/threads/$threadId'
    | '/hub/'
    | '/settings/'
    | '/settings/providers/$providerName'
    | '/settings/providers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/hub/$modelId'
    | '/settings/ax-engine'
    | '/settings/general'
    | '/threads/$threadId'
    | '/hub'
    | '/settings'
    | '/settings/providers/$providerName'
    | '/settings/providers'
  id:
    | '__root__'
    | '/'
    | '/hub/$modelId'
    | '/settings/ax-engine'
    | '/settings/general'
    | '/threads/$threadId'
    | '/hub/'
    | '/settings/'
    | '/settings/providers/$providerName'
    | '/settings/providers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HubModelIdRoute: typeof HubModelIdRoute
  SettingsAxEngineRoute: typeof SettingsAxEngineRoute
  SettingsGeneralRoute: typeof SettingsGeneralRoute
  ThreadsThreadIdRoute: typeof ThreadsThreadIdRoute
  HubIndexRoute: typeof HubIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SettingsProvidersProviderNameRoute: typeof SettingsProvidersProviderNameRoute
  SettingsProvidersIndexRoute: typeof SettingsProvidersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/': {
      id: '/hub/'
      path: '/hub'
      fullPath: '/hub/'
      preLoaderRoute: typeof HubIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threads/$threadId': {
      id: '/threads/$threadId'
      path: '/threads/$threadId'
      fullPath: '/threads/$threadId'
      preLoaderRoute: typeof ThreadsThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/settings/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/ax-engine': {
      id: '/settings/ax-engine'
      path: '/settings/ax-engine'
      fullPath: '/settings/ax-engine'
      preLoaderRoute: typeof SettingsAxEngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/$modelId': {
      id: '/hub/$modelId'
      path: '/hub/$modelId'
      fullPath: '/hub/$modelId'
      preLoaderRoute: typeof HubModelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/providers/': {
      id: '/settings/providers/'
      path: '/settings/providers'
      fullPath: '/settings/providers/'
      preLoaderRoute: typeof SettingsProvidersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/providers/$providerName': {
      id: '/settings/providers/$providerName'
      path: '/settings/providers/$providerName'
      fullPath: '/settings/providers/$providerName'
      preLoaderRoute: typeof SettingsProvidersProviderNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HubModelIdRoute: HubModelIdRoute,
  SettingsAxEngineRoute: SettingsAxEngineRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
  ThreadsThreadIdRoute: ThreadsThreadIdRoute,
  HubIndexRoute: HubIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SettingsProvidersProviderNameRoute: SettingsProvidersProviderNameRoute,
  SettingsProvidersIndexRoute: SettingsProvidersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
