name: get-update-version
on:
  workflow_call:
    inputs:
      version:
        required: false
        type: string
        default: ''
    outputs:
      new_version:
        description: 'The new version of the app'
        value: ${{ jobs.get-update-version.outputs.new_version }}

jobs:
  get-update-version:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.version_update.outputs.new_version }}
    steps:
      - name: Install jq
        uses: dcarbone/install-jq-action@v2.0.1

      - name: Update app version based on latest release tag with build number
        id: version_update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INPUT_VERSION: ${{ inputs.version }}
          GITHUB_REF: ${{ github.ref }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
        run: |
          get_latest_tag() {
            local retries=0
            local max_retries=3
            local tag
            while [ $retries -lt $max_retries ]; do
              tag=$(curl -H "Authorization: token ${GITHUB_TOKEN}" -s https://api.github.com/repos/defai-digital/ax-studio/releases/latest | jq -r .tag_name)
              if [ -n "$tag" ] && [ "$tag" != "null" ]; then
                echo "$tag"
                return
              else
                ((retries += 1))
                echo "Retrying... ($retries/$max_retries)"
                sleep 2
              fi
            done
            echo "Failed to fetch latest tag after $max_retries attempts."
            exit 1
          }

          if [ -n "$INPUT_VERSION" ]; then
            sanitized_tag="${INPUT_VERSION#v}"
            echo "Manual version requested: $sanitized_tag"
            echo "new_version=${sanitized_tag}" >> "$GITHUB_OUTPUT"
          elif [ "$GITHUB_EVENT_NAME" = "push" ] && [[ "$GITHUB_REF" == refs/tags/* ]]; then
            echo "Tag detected, set output follow tag"
            sanitized_tag="${GITHUB_REF#refs/tags/v}"
            echo "new_version=${sanitized_tag}" >> "$GITHUB_OUTPUT"
          else
            LATEST_TAG=$(get_latest_tag)
            new_version="${LATEST_TAG#v}-${GITHUB_RUN_NUMBER}"
            echo "New version: $new_version"
            echo "new_version=${new_version}" >> "$GITHUB_OUTPUT"
          fi
